version: "3.8"

services:
  celery:
    build: .
    command: celery -A tasks worker -l info 
    container_name: celery_con
    volumes:
      - .:/usr/src/app
  python:
    build: .
    command: './start.sh'
    volumes:
      - .:/usr/src/app
  redis:
    image: "redis:alpine"
    