name: Python application

on:
  push:
   branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "chheda9498" | docker login -u "paraschheda" --password-stdin
        docker image build -t dab8106/gitaction:v1 .
        docker push dab8106/gitaction:v1