name: Python application

on:
  push:
   branches: [ celery_master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        run: |
          echo "chheda9498" | docker login -u "paraschheda" --password-stdin
          docker image build -t first_git .
          docker push paraschheda/celery
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: paraschheda
          password: chheda9498
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
